# Generated by Django 5.2.11 on 2026-03-13 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("industries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rss_url", models.URLField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_sources",
                        to="industries.industry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField()),
                ("url", models.URLField(unique=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_articles",
                        to="industries.industry",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="news.newssource",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.AddIndex(
            model_name="newssource",
            index=models.Index(
                fields=["industry"], name="news_newsso_industr_3151cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["industry", "-published_at"],
                name="news_newsar_industr_21e83f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["source", "-published_at"],
                name="news_newsar_source__69bb5b_idx",
            ),
        ),
    ]
