# Generated by Django 5.2.11 on 2026-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
