# Generated by Django 5.2.11 on 2026-03-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_ai_summary_newsarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.TextField(),
        ),
    ]
