# Generated by Django 6.0.2 on 2026-02-22 04:58

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0005_organization_deleted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("META", "Meta"),
                            ("LINKEDIN", "LinkedIn"),
                            ("YOUTUBE", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("access_token", encrypted_model_fields.fields.EncryptedTextField()),
                (
                    "refresh_token",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "provider"],
                        name="social_acco_organiz_760a2d_idx",
                    ),
                    models.Index(
                        fields=["external_id"], name="social_acco_externa_e2de09_idx"
                    ),
                ],
                "unique_together": {("organization", "provider", "external_id")},
            },
        ),
    ]
