# Generated by Django 6.0.2 on 2026-02-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="last_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="refresh_failed_count",
            field=models.IntegerField(default=0),
        ),
    ]
