# Generated by Django 6.0.2 on 2026-02-23 08:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0002_socialaccount_last_refreshed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishingTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("META", "Meta"),
                            ("LINKEDIN", "LinkedIn"),
                            ("YOUTUBE", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_id", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publishing_targets",
                        to="social_accounts.socialaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider"], name="social_acco_provide_72ff80_idx"
                    ),
                    models.Index(
                        fields=["resource_id"], name="social_acco_resourc_e191fe_idx"
                    ),
                ],
                "unique_together": {("social_account", "resource_id")},
            },
        ),
    ]
