# Generated by Django 6.0.2 on 2026-02-23 09:00

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0003_publishingtarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "page_access_token",
                    encrypted_model_fields.fields.EncryptedTextField(),
                ),
                (
                    "instagram_business_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "social_account",
                    models.ForeignKey(
                        limit_choices_to={"provider": "META"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_pages",
                        to="social_accounts.socialaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["page_id"], name="social_acco_page_id_a3d62e_idx"
                    ),
                    models.Index(
                        fields=["social_account"], name="social_acco_social__372737_idx"
                    ),
                ],
                "unique_together": {("social_account", "page_id")},
            },
        ),
    ]
