# Generated by Django 6.0.2 on 2026-02-23 10:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0004_metapage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linkedin_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "vanity_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "social_account",
                    models.ForeignKey(
                        limit_choices_to={"provider": "LINKEDIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_organizations",
                        to="social_accounts.socialaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["linkedin_id"], name="social_acco_linkedi_0ed065_idx"
                    ),
                    models.Index(
                        fields=["social_account"], name="social_acco_social__1ee533_idx"
                    ),
                ],
                "unique_together": {("social_account", "linkedin_id")},
            },
        ),
    ]
