# Generated by Django 6.0.2 on 2026-02-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0005_linkedinorganization"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publishingtarget",
            unique_together={("social_account", "provider", "resource_id")},
        ),
    ]
