# Generated by Django 5.2.11 on 2026-02-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0006_alter_publishingtarget_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishingtarget",
            name="provider",
            field=models.CharField(
                choices=[
                    ("META", "Meta"),
                    ("INSTAGRAM", "Instagram"),
                    ("LINKEDIN", "LinkedIn"),
                    ("YOUTUBE", "YouTube"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("META", "Meta"),
                    ("INSTAGRAM", "Instagram"),
                    ("LINKEDIN", "LinkedIn"),
                    ("YOUTUBE", "YouTube"),
                ],
                max_length=20,
            ),
        ),
    ]
