# Generated by Django 5.2.11 on 2026-03-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0008_alter_linkedinorganization_social_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishingtarget",
            name="provider",
            field=models.CharField(
                choices=[
                    ("meta", "Meta"),
                    ("instagram", "Instagram"),
                    ("linkedin", "LinkedIn"),
                    ("youtube", "YouTube"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
