# Generated by Django 6.0.2 on 2026-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("WARNING", "Warning"),
                    ("CRITICAL", "Critical"),
                ],
                default="INFO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("TOKEN_REFRESH", "Token Refresh"),
                    ("OTP_VERIFIED", "OTP Verified"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ORG_CREATED", "Organization Created"),
                    ("ORG_DELETED", "Organization Deleted"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("ROLE_CHANGED", "Role Changed"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
