# Generated by Django 5.2.11 on 2026-02-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_auditlog_severity_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
