# Generated by Django 5.2.11 on 2026-03-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_alter_auditlog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("TOKEN_REFRESH", "Token Refresh"),
                    ("OTP_VERIFIED", "OTP Verified"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ORG_CREATED", "Organization Created"),
                    ("ORG_DELETED", "Organization Deleted"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("POST_CREATED", "Post Created"),
                    ("POST_UPDATED", "Post Updated"),
                    ("POST_DELETED", "Post Deleted"),
                    ("POST_RESTORED", "Post Restored"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
