# Generated by Django 5.2.11 on 2026-03-07 11:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0002_post_deleted_at_post_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostPlatformAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("saves", models.PositiveIntegerField(default=0)),
                ("watch_time", models.BigIntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post_platform",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="posts.postplatform",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["post_platform"], name="analytics_p_post_pl_942f25_idx"
                    )
                ],
            },
        ),
    ]
