# Generated by Django 5.2.11 on 2026-03-10 09:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("posts", "0002_post_deleted_at_post_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostPlatformAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("saves", models.PositiveIntegerField(default=0)),
                ("watch_time", models.BigIntegerField(default=0)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to="posts.postplatform",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["post_platform"], name="analytics_p_post_pl_8deaf5_idx"
                    ),
                    models.Index(
                        fields=["captured_at"], name="analytics_p_capture_138555_idx"
                    ),
                ],
            },
        ),
    ]
