# Generated by Django 5.2.11 on 2026-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_otptoken_options_user_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["expires_at"], name="authenticat_expires_8a3add_idx"
            ),
        ),
    ]
