# Generated by Django 5.2.11 on 2026-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
