# Generated by Django 6.0.2 on 2026-02-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auditlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
