# Generated by Django 5.2.11 on 2026-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_organization_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization_logos/"
            ),
        ),
    ]
